# Generated by Django 2.2 on 2020-07-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_auto_20200721_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='trip_app.Trip'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_photos', to='trip_app.Trip'),
        ),
    ]
