# Generated by Django 2.2 on 2020-07-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
