# Generated by Django 2.2 on 2020-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0003_user_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
